export enum RolesEnum {
  // IO Module
  IO_VISUALIZAR = 'ROLE_IO_VISUALIZAR',
  IO_INSERIR = 'ROLE_IO_INSERIR',
  IO_EDITAR = 'ROLE_IO_EDITAR',
  IO_APROVACAO = 'ROLE_IO_APROVACAO',
  IO_DOWNLOAD_HISTORICO = 'ROLE_IO_DOWNLOAD_HISTORICO',
  IO_OBSOLETAR = 'ROLE_IO_OBSOLETAR',
}
