export const commonIcons = [
  // Calendário e Tempo
  'i-lucide-calendar',
  'i-lucide-calendar-days',
  'i-lucide-calendar-check',
  'i-lucide-calendar-clock',
  'i-lucide-calendar-plus',
  'i-lucide-calendar-minus',
  'i-lucide-calendar-x',
  'i-lucide-clock',
  'i-lucide-timer',
  'i-lucide-alarm-clock',
  'i-lucide-hourglass',

  // Tecnologia e Hardware
  'i-lucide-wifi',
  'i-lucide-wifi-off',
  'i-lucide-bluetooth',
  'i-lucide-battery',
  'i-lucide-battery-charging',
  'i-lucide-battery-low',
  'i-lucide-power',
  'i-lucide-plug',
  'i-lucide-monitor',
  'i-lucide-smartphone',
  'i-lucide-tablet',
  'i-lucide-laptop',
  'i-lucide-server',
  'i-lucide-database',
  'i-lucide-hard-drive',
  'i-lucide-cpu',
  'i-lucide-microchip',
  'i-lucide-circuit-board',
  'i-lucide-usb',
  'i-lucide-cable',
  'i-lucide-router',

  // Desenvolvimento e Código
  'i-lucide-code',
  'i-lucide-code-2',
  'i-lucide-search-code',
  'i-lucide-message-square-code',
  'i-lucide-message-circle-code',
  'i-lucide-terminal',
  'i-lucide-terminal-square',
  'i-lucide-file-code',
  'i-lucide-file-json',
  'i-lucide-braces',
  'i-lucide-brackets',
  'i-lucide-parentheses',
  'i-lucide-chevrons-left-right',
  'i-lucide-git-branch',
  'i-lucide-git-commit',
  'i-lucide-git-merge',
  'i-lucide-git-pull-request',
  'i-lucide-github',
  'i-lucide-gitlab',
  'i-lucide-bug-play',
  'i-lucide-package-2',
  'i-lucide-package-open',
  'i-lucide-blocks',

  // Indústria e Fábrica
  'i-lucide-factory',
  'i-lucide-construction',
  'i-lucide-hard-hat',
  'i-lucide-cog',
  'i-lucide-settings-2',
  'i-lucide-combine',
  'i-lucide-component',
  'i-lucide-container',
  'i-lucide-boxes',
  'i-lucide-package-plus',
  'i-lucide-gauge',
  'i-lucide-gauge-circle',

  // Usuários e Pessoas
  'i-lucide-user',
  'i-lucide-users',
  'i-lucide-user-plus',
  'i-lucide-user-minus',
  'i-lucide-user-check',
  'i-lucide-user-x',
  'i-lucide-user-circle',
  'i-lucide-contact',
  'i-lucide-id-card',

  // Localização
  'i-lucide-map-pin',
  'i-lucide-map',
  'i-lucide-globe',
  'i-lucide-compass',
  'i-lucide-navigation',
  'i-lucide-locate',
  'i-lucide-flag',

  // Edifícios e Lugares
  'i-lucide-building',
  'i-lucide-building-2',
  'i-lucide-home',
  'i-lucide-warehouse',
  'i-lucide-store',
  'i-lucide-school',
  'i-lucide-hospital',
  'i-lucide-church',

  // Trabalho e Negócios
  'i-lucide-briefcase',
  'i-lucide-briefcase-business',
  'i-lucide-presentation',
  'i-lucide-projector',
  'i-lucide-handshake',
  'i-lucide-chart-line',
  'i-lucide-chart-bar',
  'i-lucide-chart-pie',
  'i-lucide-trending-up',
  'i-lucide-trending-down',

  // Comunicação
  'i-lucide-mail',
  'i-lucide-inbox',
  'i-lucide-send',
  'i-lucide-phone',
  'i-lucide-phone-call',
  'i-lucide-phone-incoming',
  'i-lucide-phone-outgoing',
  'i-lucide-message-square',
  'i-lucide-message-circle',
  'i-lucide-messages-square',
  'i-lucide-speech',

  // Notificações e Alertas
  'i-lucide-bell',
  'i-lucide-bell-ring',
  'i-lucide-bell-off',
  'i-lucide-alert-circle',
  'i-lucide-alert-triangle',
  'i-lucide-info',
  'i-lucide-help-circle',
  'i-lucide-check-circle',
  'i-lucide-x-circle',
  'i-lucide-ban',

  // Arquivos e Documentos
  'i-lucide-file',
  'i-lucide-file-text',
  'i-lucide-file-plus',
  'i-lucide-file-minus',
  'i-lucide-file-check',
  'i-lucide-file-x',
  'i-lucide-files',
  'i-lucide-folder',
  'i-lucide-folder-open',
  'i-lucide-folder-plus',
  'i-lucide-clipboard',
  'i-lucide-clipboard-check',
  'i-lucide-clipboard-list',

  // Favoritos e Interações
  'i-lucide-star',
  'i-lucide-heart',
  'i-lucide-thumbs-up',
  'i-lucide-thumbs-down',
  'i-lucide-bookmark',
  'i-lucide-award',
  'i-lucide-medal',
  'i-lucide-trophy',

  // Configurações e Ferramentas
  'i-lucide-settings',
  'i-lucide-sliders',
  'i-lucide-wrench',
  'i-lucide-hammer',
  'i-lucide-tool-case',
  'i-lucide-cog',

  // Segurança
  'i-lucide-shield',
  'i-lucide-shield-check',
  'i-lucide-lock',
  'i-lucide-unlock',
  'i-lucide-key',
  'i-lucide-eye',
  'i-lucide-eye-off',
  'i-lucide-fingerprint',

  // Ações
  'i-lucide-download',
  'i-lucide-upload',
  'i-lucide-share',
  'i-lucide-share-2',
  'i-lucide-link',
  'i-lucide-link-2',
  'i-lucide-copy',
  'i-lucide-scissors',
  'i-lucide-trash',
  'i-lucide-trash-2',
  'i-lucide-edit',
  'i-lucide-edit-2',
  'i-lucide-edit-3',
  'i-lucide-save',
  'i-lucide-stamp',
  'i-lucide-scan',

  // Mídia
  'i-lucide-camera',
  'i-lucide-image',
  'i-lucide-images',
  'i-lucide-video',
  'i-lucide-film',
  'i-lucide-music',
  'i-lucide-mic',
  'i-lucide-mic-off',
  'i-lucide-headphones',
  'i-lucide-volume',
  'i-lucide-volume-1',
  'i-lucide-volume-2',
  'i-lucide-volume-x',
  'i-lucide-play',
  'i-lucide-pause',
  'i-lucide-stop',
  'i-lucide-skip-back',
  'i-lucide-skip-forward',

  // Tecnologia
  'i-lucide-wifi',
  'i-lucide-wifi-off',
  'i-lucide-bluetooth',
  'i-lucide-battery',
  'i-lucide-battery-charging',
  'i-lucide-battery-low',
  'i-lucide-power',
  'i-lucide-plug',
  'i-lucide-monitor',
  'i-lucide-smartphone',
  'i-lucide-tablet',
  'i-lucide-laptop',
  'i-lucide-server',
  'i-lucide-database',
  'i-lucide-hard-drive',
  'i-lucide-cpu',

  // Navegação e Controles
  'i-lucide-refresh-cw',
  'i-lucide-rotate-cw',
  'i-lucide-rotate-ccw',
  'i-lucide-maximize',
  'i-lucide-minimize',
  'i-lucide-fullscreen',
  'i-lucide-log-out',
  'i-lucide-log-in',
  'i-lucide-menu',
  'i-lucide-more-horizontal',
  'i-lucide-more-vertical',

  // Setas e Direções
  'i-lucide-chevron-down',
  'i-lucide-chevron-up',
  'i-lucide-chevron-left',
  'i-lucide-chevron-right',
  'i-lucide-arrow-up',
  'i-lucide-arrow-down',
  'i-lucide-arrow-left',
  'i-lucide-arrow-right',
  'i-lucide-arrow-up-right',
  'i-lucide-arrow-down-left',
  'i-lucide-corner-down-left',
  'i-lucide-corner-down-right',
  'i-lucide-move',

  // Operadores
  'i-lucide-plus',
  'i-lucide-minus',
  'i-lucide-x',
  'i-lucide-check',
  'i-lucide-equal',
  'i-lucide-divide',

  // Filtros e Busca
  'i-lucide-filter',
  'i-lucide-search',
  'i-lucide-zoom-in',
  'i-lucide-zoom-out',

  // Símbolos
  'i-lucide-tag',
  'i-lucide-tags',
  'i-lucide-hash',
  'i-lucide-at-sign',
  'i-lucide-percent',

  // Finanças
  'i-lucide-calculator',
  'i-lucide-credit-card',
  'i-lucide-wallet',
  'i-lucide-banknote',
  'i-lucide-coins',
  'i-lucide-dollar-sign',
  'i-lucide-receipt',

  // Compras e E-commerce
  'i-lucide-shopping-cart',
  'i-lucide-shopping-bag',
  'i-lucide-package',
  'i-lucide-package-check',
  'i-lucide-box',

  // Transporte
  'i-lucide-truck',
  'i-lucide-plane',
  'i-lucide-car',
  'i-lucide-bike',
  'i-lucide-train',
  'i-lucide-bus',
  'i-lucide-ship',

  // Atividades
  'i-lucide-footprints',
  'i-lucide-activity',
  'i-lucide-dumbbell',

  // Comida e Bebida
  'i-lucide-coffee',
  'i-lucide-utensils',
  'i-lucide-pizza',
  'i-lucide-cake',
  'i-lucide-beer',
  'i-lucide-wine',

  // Celebração
  'i-lucide-gift',
  'i-lucide-party-popper',
  'i-lucide-sparkles',
  'i-lucide-smile',
  'i-lucide-laugh',

  // Clima
  'i-lucide-sun',
  'i-lucide-moon',
  'i-lucide-cloud',
  'i-lucide-cloud-rain',
  'i-lucide-cloud-snow',
  'i-lucide-cloud-lightning',
  'i-lucide-umbrella',
  'i-lucide-wind',
  'i-lucide-snowflake',

  // Natureza
  'i-lucide-flame',
  'i-lucide-droplet',
  'i-lucide-leaf',
  'i-lucide-tree-pine',
  'i-lucide-flower',
  'i-lucide-flower-2',
  'i-lucide-sprout',

  // Animais
  'i-lucide-bug',
  'i-lucide-fish',
  'i-lucide-cat',
  'i-lucide-dog',
  'i-lucide-bird',
  'i-lucide-rabbit',

  // Energia e Inovação
  'i-lucide-zap',
  'i-lucide-rocket',
  'i-lucide-target',
  'i-lucide-lightbulb',
  'i-lucide-wand',

  // Saúde
  'i-lucide-heart-pulse',
  'i-lucide-stethoscope',
  'i-lucide-pill',
  'i-lucide-syringe',
  'i-lucide-thermometer',

  // Educação
  'i-lucide-book',
  'i-lucide-book-open',
  'i-lucide-graduation-cap',
  'i-lucide-library',

  // Diversos
  'i-lucide-anchor',
  'i-lucide-puzzle',
  'i-lucide-gamepad',
  'i-lucide-dices',
  'i-lucide-spade',
  'i-lucide-diamond',
  'i-lucide-crown',
  'i-lucide-gem',
];
